### ISSUE TITLE
timeout support

### ISSUE THREAD

**Issue by ilovethensa** [ariscript/mc-query#2]
Support for timeout would be nice, some servers take ALOT of time to respond so it just hangs instead of quiting after like 5 seconds

**Comment by ariscript** [comment]
What features do you want timeouts added for? It would be an API-breaking change, so I do want to be careful with that.
In the meantime though, you should be able to use [`tokio::time::timeout`](https://docs.rs/tokio/latest/tokio/time/fn.timeout.html) to deal with slow or unreliable servers.

**Comment by ilovethensa** [comment]
you could make it into a feature, thats not enabled by default

**Comment by TgZ39** [comment]
This should be a feature imo.

**Comment by ariscript** [comment]
Shipping in v2.
